---
title: "Sobs Model Formulas"
author: "Will Harrod"
date: "2024-03-08"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

###Observation level model

$$
n_{observed} \sim \text{Binom}(N_{true}, \ p_{d}) 
$$

### Abondance level model

$$
N_{true} \sim \text{Pois}(\lambda)
$$

$$
\text{log}(\lambda) = \alpha + \beta_1x_1 + \beta_2x_2 +...\beta_jx_j
$$



$$
p_d \propto \sigma
$$



$$
\text{log}(\sigma) = \sigma_0 + \beta_1x_1 + \beta_2x_2 +...\beta_jx_j
$$



###Fake data
```{r}
#Add packages
library(dplyr)
library(tidyr)
library(ggplot2)
library(gridExtra)
#Generate geometric data
min_dat <- tibble(x = seq(from = 1, to = 6, by = 0.01)) %>% 
  mutate(y = x^3)

#Plot these data
min_graph <- min_dat %>% 
  ggplot(aes(x = x, y = y/max(y))) +
  geom_point() +
  theme_bw() +
  labs(x = "Minute",
        y = "Probability of detection")

#simulate a half normal detection function
#Generate geometric data
dist_dat <- tibble(x = runif(n =10000, min = 0, max = 150),
                   y = exp(-0.02 * x ))

#Plot these data
dist_graph <- dist_dat %>% 
  ggplot(aes(x = x, y = y/max(y))) +
  geom_point() +
  theme_bw() +
  xlim(0, 150) + 
  labs(x = "Distance (m)",
        y = "Probability of detection")
dist_graph
```

